/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SEC_Assignment;
import API.Plugin;
import java.lang.reflect.InvocationTargetException;
import java.util.*;
import org.python.util.PythonInterpreter;
import org.python.core.*;
public class App //implements API
{
    private static ArrayList<Plugin> pluginList = new ArrayList<Plugin>();
    public static void main(String[] args)
    {
        int menuOption = 0;
        while(menuOption != 3)
        {
            menuOption = DisplayMenu();
            if(menuOption == 1)
            {
                int pluginOption = getPluginMenuOption();
                if (pluginOption == 1)
                {
                    displayPlugins();
                }
                else if(pluginOption == 2)
                {
                   AddPlugin(pluginOption);
                }
            }
            else if(menuOption == 2)
            {
                EvaluateExpression();
            } 
        }
    }
    
    public static void AddPlugin(int pluginOption)
    {
        while(pluginOption == 2)
        {
           try
           {
              String pluginName = getPluginName();
              Class<?> pluginClass = Class.forName(pluginName);
              Plugin pluginObj = (Plugin) pluginClass.getConstructor().newInstance();
              pluginObj.setName(pluginClass.getName());
              pluginOption = 0;
              pluginList.add(pluginObj);
              System.out.println("..............................................");
              System.out.println("Successfully Loaded Plugin: " +pluginObj.getName());
              System.out.println("..............................................");
           }
           catch(ClassCastException c)
           {
               System.out.println("Class does not implement plugin, try again");
           }
           catch(NoSuchMethodException e)
           {
               System.out.println("Plugin does not exist, please try again");
           }
           catch(ClassNotFoundException f)
           {
               System.out.println("Class does not exist, please try again");
           }
           catch(InstantiationException g)
           {
               System.out.println("Something went wrong, try again");
           }
           catch(IllegalAccessException h)
           {
               System.out.println("Can't access class, try again");
           }
           catch(InvocationTargetException j)
           {
               System.out.println("Can't call class constructor, try again");
           }
        }
    }
    
    public static void displayPlugins()
    {
        if(pluginList.isEmpty())
        {
            System.out.println("..............................................");
            System.out.println("No plugins have been loaded yet");
            System.out.println("..............................................");
        }
        else
        {
            System.out.println("................Loaded Plugins................");
            for(Plugin p : pluginList)
            {
                System.out.println(p.getName());
            }
            System.out.println("..............................................");
        }
    }
    
    public static String getPluginName()
    {
        System.out.println("..........Please enter a plugin name..........");
        Scanner sc = new Scanner(System.in);
        String pluginName = sc.nextLine();
        while(pluginName.length() == 0)
        {
            System.out.println("Please enter a non-empty plugin name");
            pluginName = sc.nextLine();
        }
        System.out.println(".............................................");
        return pluginName;
    }
    
    public static int getPluginMenuOption()
    {
        boolean inputValid = false;
        int option = -1;
        do
        {
            try
            {
                System.out.println("Please type a number to select an option");
                System.out.println("1. View Plugins");
                System.out.println("2. Add Plugins");
                Scanner sc = new Scanner(System.in);
                option = sc.nextInt();
                while(option < 1 || option > 2)
                {
                    System.out.println("Please enter an integer between 1 and 2");
                    option = sc.nextInt();
                }
                inputValid = true;
            }
            catch(InputMismatchException e)
            {
                System.out.println("Please enter valid input");
            }
        }while(!inputValid);
        return option;
    }
    
    public static void EvaluateExpression()
    {
        PythonInterpreter py = new PythonInterpreter();
        String expression = getExpression();
        double minValue = getMinimumValue();
        double maxValue = getMaximumValue(minValue);
        double incrementValue = getIncrementValue();
        CalculationAPI calcApi= new CalculationAPI(expression, minValue, 
                                                    maxValue, incrementValue);
        for(Plugin p : pluginList)
        {
            p.start(calcApi);
        }
        String tempExp;
        for(String str : calcApi.getMathFunctions().keySet())
        {
            py.exec(calcApi.getMathFunctions().get(str));
        }
        for(double x = minValue; x <= maxValue; x+=incrementValue)
        {
            tempExp = expression;
            tempExp = tempExp.replace("x", Double.toString(x));
            try
            {
                double result = ((PyFloat) py.eval("float(" + tempExp + ")")).getValue();
                calcApi.setYValue(result);
                calcApi.notifyResult(x, result);
                System.out.println("Result was: " + result);
            }
            catch(PyException e)
            {
                System.out.println("Something went wrong with the calculation, please double check the input string");
            }
        }
        
    }

    private static int DisplayMenu()
    {
        int option = -1;
        boolean inputValid = false;
        do
        {
            try
            {
                System.out.println("Please type a number to select an option");
                System.out.println("1. Manage Plugins");
                System.out.println("2. Evaluate Equation");
                System.out.println("3. Exit");
                Scanner sc = new Scanner(System.in);
                option = sc.nextInt();
                while(option < 1 || option > 3)
                {
                    System.out.println("Please enter an integer between 1 and 3");
                    option = sc.nextInt();
                }
                inputValid = true;
            }
            catch(InputMismatchException e)
            {
                System.out.println("Please enter a valid number");
            }
        }while(!inputValid);
        return option;
    }
    
    private static String getExpression()
    {
        Scanner sc = new Scanner(System.in);
        System.out.println("Please enter a mathematical expression");
        String expression = sc.nextLine();
        while(!expression.contains("x"))
        {
            System.out.println("Please enter a valid expression that contains the variable x");
            expression = sc.nextLine();
        }
        return expression;
    }
    
    private static double getMinimumValue()
    {
        boolean inputValid = false;
        double option = -1.0;
        do
        {
            try
            {
                Scanner sc = new Scanner(System.in);
                System.out.println("Please enter the minimum x value");
                option = sc.nextDouble();  
                while(option < 0.0)
                {
                    System.out.println("Please enter a decimal number "
                            + "that is greater than or equal to 0");
                    option = sc.nextDouble();
                }
                inputValid = true;
            }
            catch(InputMismatchException e)
            {
                System.out.println("Invalid input, try again");
            }
        }while(!inputValid);
        return option;   
    }
    
    private static double getMaximumValue(double minValue)
    {
        boolean inputValid = false;
        double maxValue = -1;
        do{
            try
            {
                Scanner sc = new Scanner(System.in);
                System.out.println("Please enter the maximum x value");
                maxValue = sc.nextDouble();  
                while(maxValue < minValue)
                {
                    System.out.println("Please enter a value higher than " + minValue);
                    maxValue = sc.nextDouble();
                }
                inputValid = true;
            }
            catch(InputMismatchException e)
            {
                System.out.println("Invalid input, try again");
            }
        }while(!inputValid);
        return maxValue;
    }
    
    private static double getIncrementValue()
    {
        boolean inputValid = false;
        double option = -1.0;
        do
        {
            try
            {
                Scanner sc = new Scanner(System.in);
                System.out.println("Please enter the increment x value");
                option = sc.nextDouble();  
                while(option < 0.0)
                {
                    System.out.println("Please enter a decimal number "
                            + "that is greater than 0");
                    option = sc.nextDouble();
                }
                inputValid = true;
            }
            catch(InputMismatchException e)
            {
                System.out.println("Invalid input, try again");
            }
        }while(!inputValid);
        return option;
    }           
    
}